echo "<foo>"
saxon -it:main simple-oddbyexample.xsl suffix=tei corpus=/Volumes/Repo/Simple/dbnl name=dbnl
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/obvil name=obvil
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/cesr name=cesr
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/ota name=ota
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/dta name=dta
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B00 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B01 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B02 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B03 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B04 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B05 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B06 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B07 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B08 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B09 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B10 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B11 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B12 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B13 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B14 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B15 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B16 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B17 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B18 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B19 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B20 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B21 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B22 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B23 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B24 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B25 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B26 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B27 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B28 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B29 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B30 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B31 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B32 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B33 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B34 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/B36 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K00 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K01 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K02 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K03 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K04 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K05 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K06 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K07 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K08 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K09 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K10 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K11 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K12 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/K13 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N00 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N01 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N02 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N03 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N04 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N05 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N06 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N07 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N08 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N09 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N10 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N11 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N12 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N13 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N14 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N15 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N16 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N17 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N18 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N19 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N20 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N21 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N22 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N23 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N24 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N25 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N26 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N27 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N28 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N29 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N30 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N31 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N32 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N33 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N34 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N35 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N36 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/N37 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A00 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A01 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A02 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A03 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A04 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A05 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A06 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A07 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A08 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A09 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A10 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A11 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A12 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A13 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A14 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A15 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A16 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A17 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A18 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A19 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A20 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A21 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A22 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A23 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A24 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A25 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A26 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A27 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A28 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A29 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A30 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A31 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A32 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A33 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A34 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A35 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A36 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A37 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A38 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A39 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A40 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A41 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A42 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A43 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A44 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A45 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A46 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A47 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A48 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A49 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A50 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A51 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A52 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A53 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A54 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A55 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A56 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A57 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A58 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A59 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A60 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A61 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A62 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A63 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A64 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A65 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A66 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A67 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A68 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A69 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A70 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A71 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A72 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A73 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A74 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A75 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A76 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A77 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A78 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A79 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A80 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A81 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A82 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A83 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A84 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A85 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A86 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A87 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A88 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A89 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A90 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A91 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A92 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A93 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A94 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A95 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A96 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A97 name=TCP
saxon -it:main simple-oddbyexample.xsl corpus=/Volumes/Repo/Simple/TCP/A99 name=TCP
echo "</foo>"
