curl http://obvil.paris-sorbonne.fr/corpus/critique/revue-wagnerienne_tome1.xml > revue-wagnerienne_tome1.xml
curl http://obvil.paris-sorbonne.fr/corpus/critique/albalat_mal-decrire-roman-contemporain.xml  > albalat_mal-decrire-roman-contemporain.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/albalat_formation.xml  > albalat_formation.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/albalat_ennemis.xml  > albalat_ennemis.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/albalat_souvenirs.xml  > albalat_souvenirs.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/albalat_comment.xml  > albalat_comment.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/barbey-aurevilly_goethe-diderot.xml  > barbey-aurevilly_goethe-diderot.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/barbey-aurevilly_poesie.xml  > barbey-aurevilly_poesie.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/barbey-aurevilly_voyageurs-et-romanciers.xml  > barbey-aurevilly_voyageurs-et-romanciers.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/barbey-aurevilly_philosophes.xml  > barbey-aurevilly_philosophes.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/barine_musset.xml  > barine_musset.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/barres_taine.xml  > barres_taine.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/barres_familles.xml  > barres_familles.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bashkirtseff_lettres.xml  > bashkirtseff_lettres.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bazalgette_esprit.xml  > bazalgette_esprit.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bazalgette_latin.xml  > bazalgette_latin.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/beaunier_poesie.xml  > beaunier_poesie.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/becq-de-fouquieres_art-mise-en-scene.xml  > becq-de-fouquieres_art-mise-en-scene.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bergson_conscience.xml  > bergson_conscience.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bergson_matiere.xml  > bergson_matiere.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bergson_rire.xml  > bergson_rire.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bergson_evolution.xml  > bergson_evolution.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bergson_france.xml  > bergson_france.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bergson_energie.xml  > bergson_energie.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bergson_duree.xml  > bergson_duree.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bergson_sources.xml  > bergson_sources.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bergson_pensee.xml  > bergson_pensee.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bernard_introduction-medecine-experimentale.xml  > bernard_introduction-medecine-experimentale.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bourget_etudes1.xml  > bourget_etudes1.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bourget_etudes3.xml  > bourget_etudes3.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bourget_temoignages.xml  > bourget_temoignages.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bourget_temoignages-2.xml  > bourget_temoignages-2.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/bremond_poesie-pure.xml  > bremond_poesie-pure.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/brunetiere_evolution-des-genres.xml  > brunetiere_evolution-des-genres.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/caro_sand.xml  > caro_sand.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/crevel_esprit-contre-raison.xml  > crevel_esprit-contre-raison.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/crevel_clavecin-diderot.xml  > crevel_clavecin-diderot.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/daudet-leon_stupide19e.xml  > daudet-leon_stupide19e.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/deschanel_physiologie.xml  > deschanel_physiologie.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/deschanel_romantisme.xml  > deschanel_romantisme.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/diderot_salon1759.xml  > diderot_salon1759.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/diderot_salon1761.xml  > diderot_salon1761.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/diderot_salon1763.xml  > diderot_salon1763.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/diderot_essais-peinture1765.xml  > diderot_essais-peinture1765.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/diderot_salon1767.xml  > diderot_salon1767.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/diderot_claude-neron.xml  > diderot_claude-neron.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/diderot_plan-universite.xml  > diderot_plan-universite.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/doumic_ecrivains.xml  > doumic_ecrivains.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/doumic_jeunes.xml  > doumic_jeunes.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/dubos_critiques.xml  > dubos_critiques.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/dumarsais_tropes.xml  > dumarsais_tropes.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/dupuy_poetes-et-critiques.xml  > dupuy_poetes-et-critiques.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/egger_parole.xml  > egger_parole.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/equilbecq_litterature-merveilleuse-des-noirs.xml  > equilbecq_litterature-merveilleuse-des-noirs.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/faguet_politique-comparee.xml  > faguet_politique-comparee.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/faguet_anticlericalisme.xml  > faguet_anticlericalisme.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/faguet_rousseau-contre-moliere.xml  > faguet_rousseau-contre-moliere.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/faguet_la-fontaine.xml  > faguet_la-fontaine.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/faguet_art-de-lire.xml  > faguet_art-de-lire.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/flat_femmes.xml  > flat_femmes.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gaultier_bovarysme.xml  > gaultier_bovarysme.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gautier_portraits-contemporains.xml  > gautier_portraits-contemporains.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gheon_directions.xml  > gheon_directions.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/ghil_poesie-scientifique.xml  > ghil_poesie-scientifique.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/ghil_dates-et-oeuvres.xml  > ghil_dates-et-oeuvres.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gourmont_masques1.xml  > gourmont_masques1.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gourmont_masques2.xml  > gourmont_masques2.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gourmont_langue.xml  > gourmont_langue.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gourmont_chemin.xml  > gourmont_chemin.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gourmont_style.xml  > gourmont_style.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gourmont_promenades-philosophiques-1.xml  > gourmont_promenades-philosophiques-1.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gourmont_promenades-philosophiques-2.xml  > gourmont_promenades-philosophiques-2.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/gourmont_promenades-philosophiques-3.xml  > gourmont_promenades-philosophiques-3.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/hennequin_quelques-ecrivains-francais.xml  > hennequin_quelques-ecrivains-francais.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/hennequin_ecrivains-francises.xml  > hennequin_ecrivains-francises.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/jarry_divers.xml  > jarry_divers.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/la-grange_preface.xml  > la-grange_preface.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/la-harpe_racine.xml  > la-harpe_racine.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/la-motte_poesie.xml  > la-motte_poesie.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/la-motte_homere.xml  > la-motte_homere.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/la-motte_critique.xml  > la-motte_critique.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/la-motte_tragedie.xml  > la-motte_tragedie.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lanson_methodes.xml  > lanson_methodes.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lasserre_romantiques.xml  > lasserre_romantiques.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_contemporains1.xml  > lemaitre_contemporains1.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_contemporains2.xml  > lemaitre_contemporains2.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_contemporains3.xml  > lemaitre_contemporains3.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_impressions-08.xml  > lemaitre_impressions-08.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_contemporains6.xml  > lemaitre_contemporains6.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_impressions-09.xml  > lemaitre_impressions-09.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_impressions-10.xml  > lemaitre_impressions-10.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_contemporains4.xml  > lemaitre_contemporains4.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_contemporains5.xml  > lemaitre_contemporains5.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/lemaitre_contemporains7.xml  > lemaitre_contemporains7.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/martin-du-gard-maurice_feux-tournants.xml  > martin-du-gard-maurice_feux-tournants.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/morice_demain-questions-esthetique.xml  > morice_demain-questions-esthetique.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/murger_propos-ville.xml  > murger_propos-ville.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/pardo-bazan_naturalisme.xml  > pardo-bazan_naturalisme.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/pierre-quint_droits-ecrivains.xml  > pierre-quint_droits-ecrivains.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/regnier_portraits.xml  > regnier_portraits.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/regnier_proses.xml  > regnier_proses.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/regnier_de-mon-temps.xml  > regnier_de-mon-temps.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/renan_vie-de-jesus.xml  > renan_vie-de-jesus.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/renan_nation.xml  > renan_nation.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/renan_reforme.xml  > renan_reforme.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/renan_souvenirs.xml  > renan_souvenirs.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/renan_avenir-science.xml  > renan_avenir-science.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/renard_critique.xml  > renard_critique.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/ribot_attention.xml  > ribot_attention.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/rod_assommoir.xml  > rod_assommoir.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/rod_idees-morales.xml  > rod_idees-morales.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/rod_essai-sur-goethe.xml  > rod_essai-sur-goethe.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/sainte-beuve_portraits-01.xml  > sainte-beuve_portraits-01.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/sainte-beuve_portraits-02.xml  > sainte-beuve_portraits-02.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/sainte-beuve_portraits-03.xml  > sainte-beuve_portraits-03.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/st-victor_masques1.xml  > st-victor_masques1.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/st-victor_hommes-dieux.xml  > st-victor_hommes-dieux.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/st-victor_theatre.xml  > st-victor_theatre.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/souday_gide.xml  > souday_gide.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/taine_la-fontaine.xml  > taine_la-fontaine.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/taine_litterature-anglaise1.xml  > taine_litterature-anglaise1.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/taine_france-t1.xml  > taine_france-t1.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/taine_derniers-essais.xml  > taine_derniers-essais.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/thibaudet_reflexions.xml  > thibaudet_reflexions.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/wilde_derniers-essais-litterature.xml  > wilde_derniers-essais-litterature.xml 
curl http://obvil.paris-sorbonne.fr/corpus/critique/zola_naturalisme.xml  > zola_naturalisme.xml 
